name: Scala CI

on:
  push:
    branches: ["permasense2-jdk-11-gsn-services"]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'sbt'
    
    - name: compile
      run: sbt compile
      retries: 3
    
    - name: start core
      working-directory: core
      run: sbt re-start
        
    - name: Run tests
      run: sbt test

